
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/myparking
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myparking
    username: root
    password: 1234

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
  #     show_sql: true
        format_sql: true

  data:
    rest:
      base-path: /api
      default-page-size: 6
      max-page-size: 6

  profiles:
    include: oauth

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

# Spring Doc Config
springdoc:
  api-docs:
    path: /api-docs #doc default path : /v3/api-docs
    groups.enabled: true
  swagger-ui:
    path: /swagger-ui.html #swagger default path : /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
